### ISSUE TITLE
Would you like to share the Twitter dataset with us?

### ISSUE THREAD

**Issue by ngc7023** [datquocnguyen/LFTM#10]
I notice that TACL-datasets.zip does not contain the Twitter dataset used in your paper and the link you offered for downloading is invalid(http://www.sananalytics.com/lab/index.php). It would be a great help if you could share the Twitter dataset with us. ^_^

**Comment by datquocnguyen** [comment]
https://stackoverflow.com/questions/26878777/unable-to-download-the-twitter-sentiment-corpus-by-niek-sanders
