### ISSUE TITLE
InvalidOptimizableException: zero slope ???

### ISSUE THREAD

**Issue by bwang482** [datquocnguyen/LFTM#5]
Hi Dat Quoc, thanks for your great work!

I have tried to perform topic modelling on my twitter corpus using LFDMM:
`java -jar jar/LFTM.jar -model LFDMM -corpus fsd/preprocessed_tweets.txt -vectors embeddings/glove.twitter.word2vec.27B.100d.txt -ntopics 100 -name LFDMM -lambda 1.0 -twords 10`

But I keep getting `cc.mallet.optimize.InvalidOptimizableException: Slope = 0.0 is zero` exceptions:

> 	Initial sampling iteration: 2000
> 	LFDMM sampling iteration: 1
> 		Estimating topic vectors ...
> L-BFGS initial gradient is zero; saying converged
> L-BFGS initial gradient is zero; saying converged
> L-BFGS initial gradient is zero; saying converged
> L-BFGS initial gradient is zero; saying converged
> L-BFGS initial gradient is zero; saying converged
> L-BFGS initial gradient is zero; saying converged
> 	LFDMM sampling iteration: 2
> 		Estimating topic vectors ...
> L-BFGS initial gradient is zero; saying converged
> L-BFGS initial gradient is zero; saying converged
> L-BFGS initial gradient is zero; saying converged
> cc.mallet.optimize.InvalidOptimizableException: Slope = 0.0 is zero
> 	at cc.mallet.optimize.BackTrackLineSearch.optimize(BackTrackLineSearch.java:112)
> 	at utility.LBFGS.optimize(Unknown Source)
> 	at models.LFDMM$1.compute(Unknown Source)
> 	at utility.Parallel$LoopIntAction.compute(Unknown Source)
> 	at utility.Parallel$LoopIntAction.compute(Unknown Source)
> 	at utility.Parallel$LoopIntAction.compute(Unknown Source)
> 	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
> 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
> 	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:389)
> 	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
> 	at utility.Parallel$LoopIntAction.compute(Unknown Source)
> 	at utility.Parallel$LoopIntAction.compute(Unknown Source)
> 	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
> 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
> 	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:389)
> 	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
> 	at utility.Parallel$LoopIntAction.compute(Unknown Source)
> 	at utility.Parallel$LoopIntAction.compute(Unknown Source)
> 	at utility.Parallel$LoopIntAction.compute(Unknown Source)
> 	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
> 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
> 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
> 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
> 

Why? Do I need to use different settings for alpha and beta instead of the default ones? TFLDA seems to work fine.

Thanks.

**Comment by datquocnguyen** [comment]
I do not really know. LFDMM should work when LFLDA works. As you can see, the error is because of the optimization of topic vectors when using L-BFGS. One possible reason due to some unexpected initial counts for estimating topic vectors. Following [1], you might also want to try `beta = 0.1` for short texts, producing a different set of initial counts when estimating topic vectors. Or you might also want to try `lambda = 0.6`.

[1] A dirichlet multinomial mixture model-based approach for short text clustering. KDD 2014.

**Comment by bwang482** [comment]
Thanks Dat Quoc! I am still getting the same exceptions from using L-BFGS. 

But you're right, with `beta = 0.1` and `lamda = 0.6` I do get the best performance on my Twitter data.

I shall close this issue. Thanks again :)
