### ISSUE TITLE
How to evaluate topic coherence?

### ISSUE THREAD

**Issue by iwangjian** [datquocnguyen/LFTM#7]
Hi, I'm a little confused about how to compute **_NPMI_**-score to evaluate topic coherence in your paper, is there any code to evaluate?

**Comment by datquocnguyen** [comment]
I did not backup my implementation for computing NPMI. But it is relatively straightforward to reimplement that. See my answer for:  https://stats.stackexchange.com/questions/158790/topic-similarity-semantic-pmi-between-two-words-wikipedia
