### ISSUE TITLE
LFDMM prediction is vector of NaN for long document

### ISSUE THREAD

**Issue by strnam** [datquocnguyen/LFTM#8]
Hi a Dat Quoc,

Many thank for your work. 

I run LFDMM algorithm on my corpus that mixing short documents and long documents. Checking file LFDMM.theta I found that with the long document that contain more than 76 words the result for that document in file LFDMM.theta is list of NaN
"NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN"

Is there any threshold for the length of document for LFDMM algorithm? I look at the source code but still not figure out where it happen.

Hope to see your response.
Thank a Dat Quoc

**Comment by datquocnguyen** [comment]
I am not really sure what happened as I had not evaluated the LFDMM model on long documents yet.
