### ISSUE TITLE
Dataset is not accessible

### ISSUE THREAD

**Issue by ngc7023** [datquocnguyen/LFTM#9]
When I try to visit the web page: http://web.science.mq.edu.au/~dqnguyen/papers/TACL-datasets.zip

It returns:
Forbidden Error 403
Sorry, it doesn't look like you have access to this page. You may need to be on campus or using a VPN connection in order to access this page. Please contact us for more information.

How to solve this problem?

**Comment by datquocnguyen** [comment]
http://people.eng.unimelb.edu.au/dqnguyen/resources/TACL-datasets.zip

**Comment by ngc7023** [comment]
> http://people.eng.unimelb.edu.au/dqnguyen/resources/TACL-datasets.zip

That helps a lot!

In addition, I notice that TACL-datasets.zip does not contain the Twitter dataset used in your paper and the link you offered for downloading is invalid(http://www.sananalytics.com/lab/index.php). It would be a great help if you could share the Twitter dataset with us. ^_^
